# Generated by Django 6.0.2 on 2026-02-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedChatThread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('System', 'System'), ('User', 'User'), ('Assistant', 'Assistant')], max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='RestaurantSimulator.simulatedchatthread')),
            ],
        ),
    ]
