# Generated by Django 6.0.2 on 2026-02-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantSimulator', '0003_alter_chatmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedchatthread',
            name='extracted_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
