# Generated by Django 6.0.2 on 2026-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantSimulator', '0005_chatmessage_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
