# Generated by Django 6.0.2 on 2026-02-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantSimulator', '0006_chatmessage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
