
x-base: &base
  build: .
  volumes:
    - .:/home/pn/app
  environment:
    - DEBUG=True

services:
  tailwind-watcher:
    <<: *base
    command: bash -c "python manage.py tailwind install && python manage.py tailwind start"

  django-dev-server:
    <<: *base
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
